name: PluginHub
options:
  bundleIdPrefix: com.pluginhub
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    CFBundleDevelopmentRegion: en
    CFBundleAllowMixedLocalizations: YES

targets:
  PluginHub:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Resources/Assets.xcassets
      - path: Resources/en.lproj/Localizable.strings
      - path: Resources/zh-Hans.lproj/Localizable.strings
    settings:
      base:
        PRODUCT_NAME: PluginHub
        PRODUCT_BUNDLE_IDENTIFIER: com.pluginhub.macos
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "-"
        COMBINE_HIDPI_IMAGES: YES
    dependencies: []
    postCompileScripts: []

  PluginHubTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pluginhub.macos.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/PluginHub.app/Contents/MacOS/PluginHub"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSPrincipalClass: ""
    dependencies:
      - target: PluginHub

schemes:
  PluginHub:
    build:
      targets:
        PluginHub: all
        PluginHubTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - PluginHubTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
